api_hash: 6dfa36c2f8d501471a9012cdf95e3580
api_id: 7695745
chat_id: -1001979807081
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
